### PR TITLE
Add description to boxes.

### LINKED ISSUE #10: Add some explanations to the block status
It's not immediately clear what the numbers on top indicate. We should add a few lines of explanation text.

Ethereum -> Best: `Best Block on the Ethereum network (source chain)`
Bridge -> Best: `Best block of ETH network as seen by Substrate network. I.e. Best block relayed by the bridge`.
Bridge -> Finalized: `Latest finalized block of the ETH network as seen by the Substrate network.`
Substrate -> Best: `Best block of the Substrate network (target chain)`.

### PR DESCRIPTION
**Pull request by tomusdrw**
Resolves #10

### CODE REVIEW

**Comment by Tbaut** [comment]
Here is how it looks like with the helper tooltips:
image

My 2 cents on the design. I feel like this nested Bridge Pallet in Substrate makes things complex visually.
What I keep in mind is:
ETH network -> bridge -> Substrate network.

I found it quite important to have those 3 elements. Now with only 2 and this nesting, I'm actually not sure at what I'm looking at any more. Although I understand it's probably closer to the implementation reality (the bridge being a pallet on the substrate network)).

Anyway, it's up to you, if this is explained in any demo you do, and it can help the dev actually visualize better the actual implementation, then it's fine. If the target audience is a little broader, we should ask a designer to help probably :)

**Review by Tbaut — APPROVED** [review]

**Comment by tomusdrw** [comment]
> I found it quite important to have those 3 elements. Now with only 2 and this nesting, I'm actually not sure at what I'm looking at any more.

The thing is that, the `Bridge` is not something external to the network, it's just the Substrate's network perspective of the ETH network, hence it's included there. When speaking with @HCastano and @JoshOrndorff they've actually found the previous design a bit confusing. Guys can you let me know which of these two you prefer?

> Anyway, it's up to you, if this is explained in any demo you do, and it can help the dev actually visualize better the actual implementation, then it's fine. If the target audience is a little broader, we should ask a designer to help probably :)

100% agree. The main point of the UI currently is to demo the Bridge during Substrate Seminar, so I think it's mostly up to Hernando what he thinks will help him convey his points :)co

**Comment by JoshOrndorff** [comment]
I think this is an improvement for the reason @tomusdrw explained.

Actually, shouldn't there be a corresponding nested box inside of the Ethereum box that shows the Ethereum chain's view of the Substrate chain? It is a symmetrical two-way bridge right? I think a symmetric UI would really help communicate that.

**Comment by JoshOrndorff** [comment]
Really there are four pieces of information that are relevant:

* The Ethereum chain's own state (currently the left box)
* The Substrate chain's own state (currently the outer part of the right box)
* The Ethereum chain's state as far as it is known by the Substrate chain (the nested right box)
* The Substrate chain's state as far as it is known by the Ethereum chain (not currently shown, I suggest a nested left box)

**Comment by tomusdrw** [comment]
> Actually, shouldn't there be a corresponding nested box inside of the Ethereum box that shows the Ethereum chain's view of the Substrate chain? It is a symmetrical two-way bridge right? I think a symmetric UI would really help communicate that.

Yes, however the UI and the corresponding bridge application (CurrencyExchange) works only in one way (ETH -> SUB), hence we only focus on this use case.

There is an issues to work on the other direction as well: https://github.com/paritytech/parity-bridges-common/issues/320 but currently IMHO it's outside of the scope.

**Pull request merged**
